---
#- name: Check Ansible version
#  command: ansible --version
#  register: ansibleVersion

#- name: Print version
#  debug:
#    msg: "Ansible Version: {{ ansibleVersion.stdout }}"

- import_tasks: user.yml
  tags: [hadoop_docker_local, user]
