---
#Run local hadoop cluster
- name: Run using a project directory
  hosts: docker_elk_group
  gather_facts: false
  become: true

  roles:
    - role: roles/elk_local
  #connection: local
#  gather_facts: no
#  tasks:
#  - include_role:
#      name: local_docker
    #register: output

    #- debug:
    #  var: output

#
